name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-arch:
    name: Build on Arch
    runs-on: ubuntu-latest
    container: archlinux:multilib-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman-key --init
          pacman -Syu --needed --noconfirm mingw-w64-gcc meson ninja wine
      - name: Build
        run: |
          export DESTDIR="${PWD}"
          ./build.sh --install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-nvml-arch
          path: usr/**
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    container: ubuntu:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y wget
          wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
          wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          dpkg --add-architecture i386
          apt-get update
          apt-get -y install curl gcc-multilib mingw-w64 meson ninja-build wine-devel-amd64 wine-devel-i386 wine-devel-dev winehq-devel
      - name: Build
        run: |
          export DESTDIR="${PWD}"
          ./build.sh --install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-nvml-ubuntu-noble
          path: usr/**
